name: Simple TikTok RSS
on:
  workflow_dispatch:
  schedule:
    - cron: '10 */2 * * *'

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Create RSS directory
        run: mkdir -p rss
      
      - name: Generate basic RSS feeds
        run: |
          python3 << 'EOF'
          import os
          from datetime import datetime
          
          # Read usernames
          with open('subscriptions.csv', 'r') as f:
              usernames = [line.strip() for line in f if line.strip() and not line.startswith('#')]
          
          # Create RSS directory
          os.makedirs('rss', exist_ok=True)
          
          # Generate basic RSS for each user
          for username in usernames:
              rss_content = f'''<?xml version="1.0" encoding="UTF-8"?>
          <rss version="2.0">
            <channel>
              <title>TikTok - @{username}</title>
              <description>Latest videos from @{username}</description>
              <link>https://www.tiktok.com/@{username}</link>
              <pubDate>{datetime.now().strftime('%a, %d %b %Y %H:%M:%S GMT')}</pubDate>
              <item>
                <title>Sample video from {username}</title>
                <link>https://www.tiktok.com/@{username}/video/sample</link>
                <description>This is a placeholder RSS feed. Real TikTok data requires API access.</description>
                <pubDate>{datetime.now().strftime('%a, %d %b %Y %H:%M:%S GMT')}</pubDate>
                <guid>sample-{username}-{datetime.now().strftime('%Y%m%d')}</guid>
              </item>
            </channel>
          </rss>'''
              
              with open(f'rss/{username}.xml', 'w') as f:
                  f.write(rss_content)
              
              print(f"Generated RSS for {username}")
          
          print("RSS generation complete!")
          EOF
      
      - name: Commit and push RSS files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rss/
          git commit -m "Update RSS feeds $(date)" || exit 0
          git push
