name: Flat Data TikTok RSS
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 */2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.tiktok.com
          downloaded_filename: tiktok-data.json
          postprocess: postprocessing.js
